# ansible/nginx-installation.yml

---
- name: Install Nginx on EC2 Instance
  hosts: jenkins-server  
  become: true

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Start Nginx service
      service:
        name: nginx
        state: started

    - name: Enable Nginx service to start on boot
      service:
        name: nginx
        enabled: yes
